### ISSUE TITLE
The mod does not show up under active mods on browser

### ISSUE THREAD

**Issue by yungyens** [WesCook/ForgotMyHat#1]
Hi,

Since today the menu for the mod settings does no longer show up on browser (firefox). It was working all fine until yesterday. The only change I made, was changing the timer for notification, and then the settings menu was gone today when I reopened the game.

**Comment by WesCook** [comment]
It's likely that the mod was not loading correctly due to a recent game-breaking update (see #2).  An update with a fix has been pushed now.  Can you verify if the issue is still occuring on your end?

If you're still seeing a problem, I'll need you to provide some more information.  Can you include which platform you are playing on, and what other mods do you have installed?  That would be the best place to start.

Cheers.

**Comment by yungyens** [comment]
I saw you type in discord you were working on a fix or something, so today its working, all good! appreciate it

**Comment by WesCook** [comment]
Glad to hear it's working for you now.  Thanks for the update.
